"""
01_preprocess_data.py
---------------------
Reads per-wave/group raw CSV files exported from EEGLAB (MATLAB),
keeps only the Frontal electrode, reshapes to wide format, and
produces a single combined dataset: EEG_ALL_GROUPS.csv.

Expected raw file naming convention:
    <wave>_REG_<group>.csv   e.g.  Alpha_REG_Music.csv
    <wave>_IND_<group>.csv

Expected raw file structure (semicolon-delimited, skip first row):
    Name              Frontal  Central  ...
    001_BL01.set      -7.25    ...
    001_BL02.set      -7.47    ...
    ...

Output columns:
    Participant | BL01 | BL02 | BL03 | BL04 | IBOE | Group | Wave

Usage:
    python 01_preprocess_data.py --input_dir /path/to/raw_csvs --output_dir data/
"""

import argparse
import glob
import os

import pandas as pd

# Columns generated by EEGLAB that are not needed
COLS_TO_DROP = [
    "#Epochs", "#Ephocs",
    "Central", "RightTemporal", "LeftTemporal",
    "TempDir", "TempEsq",
    "Parietal", "Occipital", "Ocipita",
]


def detect_group(filename: str) -> str | None:
    name = filename.lower()
    if "nomusic" in name:
        return "NoMusic"
    if "music" in name:
        return "Music"
    return None


def detect_wave(filename: str) -> str | None:
    name = filename.lower()
    if "alpha" in name:
        return "Alpha"
    if "beta" in name:
        return "Beta"
    if "delta" in name:
        return "Delta"
    if "theta" in name:
        return "Theta"
    return None


def process_file(filepath: str, group: str, wave: str) -> pd.DataFrame:
    df = pd.read_csv(filepath, header=1, sep=";")
    df = df.drop(columns=[c for c in COLS_TO_DROP if c in df.columns])

    df["Frontal"] = (
        df["Frontal"]
        .astype(str)
        .str.replace(r'(-?\d+\.\d{3})\.(\d+)', r'\1\2', regex=True)
    )
    df["Frontal"] = pd.to_numeric(df["Frontal"], errors="coerce")

    df[["Participant", "Condition"]] = (
        df["Name"]
        .str.replace(".set", "", regex=False)
        .str.split("_", expand=True)
    )

    df_wide = (
        df.pivot(index="Participant", columns="Condition", values="Frontal")
        .reset_index()
    )
    df_wide["Group"] = group
    df_wide["Wave"] = wave
    return df_wide


def main(input_dir: str, output_dir: str) -> None:
    files = glob.glob(os.path.join(input_dir, "**", "*.csv"), recursive=True)
    frames = []

    for filepath in files:
        filename = os.path.basename(filepath)
        group = detect_group(filename)
        wave = detect_wave(filename)
        if group is None or wave is None:
            continue

        df = process_file(filepath, group, wave)
        frames.append(df)
        print(f"  Processed: {filename}  ({group}, {wave}, {len(df)} participants)")

    if not frames:
        print("No matching CSV files found. Check --input_dir and file naming.")
        return

    combined = pd.concat(frames, ignore_index=True)

    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, "EEG_ALL_GROUPS.csv")
    combined.to_csv(out_path, index=False)
    print(f"\nSaved combined dataset ({len(combined)} rows) -> {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Preprocess raw EEGLAB CSVs.")
    parser.add_argument(
        "--input_dir",
        default="raw_data",
        help="Directory containing the raw per-wave/group CSV files.",
    )
    parser.add_argument(
        "--output_dir",
        default="data",
        help="Directory where EEG_ALL_GROUPS.csv will be saved.",
    )
    args = parser.parse_args()
    main(args.input_dir, args.output_dir)
